# -*- coding: utf-8 -*-
"""BuildaGeotiffRasterwProjection.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ZBFb1hymmhbjLL4C9O3CP3VX6KcjrvJQ
"""

from osgeo import gdal
import pandas as pd
import numpy as np

#if there is another Geotiff already obtaining the correct projection
#get the projection and coordinate from an existing GeoTiff
gt = xdata.GetGeoTransform()   #xdata should be the GeoTiff
pr = xdata.GetProjection()

#Create a new GDal dataset with the same projection and coordinate
driver = gdal.GetDriverByName("GTiff")
output = driver.Create("output.tif", xnum, ynum)   #xnum and ynum should be the x-dimention and y-dimention
output.SetGeoTransform(gt)
output.SetProjection(pr)


#set one band
output_band = output.GetRasterBand(1)
output_band = WriteArray(HgtArray)

#save raster
output_band.FlushCache()
output = None